# Generated by Django 5.2 on 2025-05-25 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
         ('responsable_filiere', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi'), ('SAM', 'Samedi')], max_length=3)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('professeur', models.CharField(max_length=100)),
                ('salle', models.CharField(blank=True, max_length=50)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='responsable_filiere.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='responsable_filiere.matiere')),
            ],
            options={
                'verbose_name': 'Emploi du Temps',
                'verbose_name_plural': 'Emplois du Temps',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_evaluation', models.CharField(choices=[('DEVOIR', 'Devoir'), ('EXAMEN', 'Examen'), ('TP', 'Travail Pratique'), ('PROJET', 'Projet')], max_length=20)),
                ('date_evaluation', models.DateField()),
                ('duree', models.DurationField()),
                ('description', models.TextField(blank=True)),
                ('coefficient', models.IntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='responsable_filiere.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='responsable_filiere.matiere')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['date_evaluation'],
            },
        ),
    ]
