# Generated by Django 5.2 on 2025-05-25 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responsable_filiere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type_absence', models.CharField(choices=[('COURS', 'Cours'), ('TP', 'Travaux Pratiques'), ('EXAMEN', 'Examen'), ('AUTRE', 'Autre')], default='COURS', max_length=10)),
                ('heure_debut', models.TimeField(help_text="Heure de début de l'absence")),
                ('heure_fin', models.TimeField(help_text="Heure de fin de l'absence")),
                ('justifiee', models.BooleanField(default=False)),
                ('motif', models.TextField(blank=True, help_text="Motif de l'absence")),
                ('date_justification', models.DateField(blank=True, null=True)),
                ('document_justificatif', models.FileField(blank=True, help_text='Document justificatif (certificat médical, etc.)', null=True, upload_to='justificatifs/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences_classe', to='responsable_filiere.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences_classe', to='responsable_filiere.matiere')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date', '-heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type_observation', models.CharField(choices=[('POSITIVE', 'Observation positive'), ('NEGATIVE', 'Observation négative'), ('NEUTRE', 'Observation neutre'), ('DISCIPLINAIRE', 'Observation disciplinaire')], max_length=15)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('action_menee', models.TextField(blank=True, help_text='Action menée suite à cette observation')),
                ('suivi_necessaire', models.BooleanField(default=False, help_text='Un suivi est-il nécessaire ?')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='responsable_filiere.eleve')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='responsable_filiere.matiere')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_projet', models.CharField(choices=[('DEVOIR', 'Devoir'), ('PROJET', 'Projet'), ('EXPOSE', 'Exposé'), ('RAPPORT', 'Rapport'), ('TP', 'Travail Pratique')], default='DEVOIR', max_length=10)),
                ('statut', models.CharField(choices=[('ATTRIBUE', 'Attribué'), ('EN_COURS', 'En cours'), ('RENDU', 'Rendu'), ('CORRIGE', 'Corrigé'), ('ARCHIVE', 'Archivé')], default='ATTRIBUE', max_length=10)),
                ('date_attribution', models.DateField(default=django.utils.timezone.now)),
                ('date_limite', models.DateField()),
                ('coefficient', models.PositiveIntegerField(default=1, help_text='Coefficient pour la notation')),
                ('consignes', models.TextField(blank=True, help_text='Consignes détaillées')),
                ('fichier_sujet', models.FileField(blank=True, null=True, upload_to='sujets/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_classe', to='responsable_filiere.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_classe', to='responsable_filiere.matiere')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['date_limite'],
            },
        ),
        migrations.CreateModel(
            name='Retard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('heure_arrivee', models.TimeField(help_text="Heure d'arrivée de l'élève")),
                ('heure_prevue', models.TimeField(help_text='Heure prévue du cours')),
                ('motif', models.TextField(blank=True, help_text='Motif du retard')),
                ('justifie', models.BooleanField(default=False)),
                ('sanction', models.TextField(blank=True, help_text='Sanction éventuelle')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retards', to='responsable_filiere.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retards', to='responsable_filiere.matiere')),
            ],
            options={
                'verbose_name': 'Retard',
                'verbose_name_plural': 'Retards',
                'ordering': ['-date', '-heure_arrivee'],
            },
        ),
        migrations.CreateModel(
            name='CahierTexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('titre', models.CharField(help_text='Titre de la séance', max_length=200)),
                ('contenu', models.TextField(help_text='Contenu de la séance')),
                ('travail_a_faire', models.TextField(blank=True, help_text='Travail à faire pour la prochaine séance')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cahiers_classe', to='responsable_filiere.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cahiers_classe', to='responsable_filiere.matiere')),
            ],
            options={
                'verbose_name': 'Cahier de texte',
                'verbose_name_plural': 'Cahiers de texte',
                'ordering': ['-date'],
                'unique_together': {('classe', 'matiere', 'date', 'titre')},
            },
        ),
        migrations.CreateModel(
            name='RenduProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rendu', models.DateTimeField(default=django.utils.timezone.now)),
                ('fichier_rendu', models.FileField(blank=True, null=True, upload_to='rendus/')),
                ('commentaire_eleve', models.TextField(blank=True, help_text="Commentaire de l'élève")),
                ('note', models.DecimalField(blank=True, decimal_places=2, help_text='Note sur 20', max_digits=4, null=True)),
                ('commentaire_professeur', models.TextField(blank=True, help_text='Commentaire du professeur')),
                ('date_correction', models.DateTimeField(blank=True, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendus_projets', to='responsable_filiere.eleve')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendus', to='responsable_classe.projet')),
            ],
            options={
                'verbose_name': 'Rendu de projet',
                'verbose_name_plural': 'Rendus de projets',
                'ordering': ['-date_rendu'],
                'unique_together': {('projet', 'eleve')},
            },
        ),
    ]
