# Generated by Django 5.2 on 2025-05-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsable_classe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['-date', '-heure_debut'], 'permissions': [('can_manage_absences', 'Peut gérer les absences'), ('can_view_own_absences', 'Peut voir ses propres absences')], 'verbose_name': 'Absence', 'verbose_name_plural': 'Absences'},
        ),
        migrations.AlterModelOptions(
            name='cahiertexte',
            options={'ordering': ['-date'], 'permissions': [('can_manage_cahier_texte', 'Peut gérer le cahier de texte')], 'verbose_name': 'Cahier de texte', 'verbose_name_plural': 'Cahiers de texte'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-date'], 'permissions': [('can_manage_observations', 'Peut gérer les observations'), ('can_view_own_observations', 'Peut voir ses propres observations')], 'verbose_name': 'Observation', 'verbose_name_plural': 'Observations'},
        ),
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['date_limite'], 'permissions': [('can_manage_projets', 'Peut gérer les projets')], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='renduprojet',
            options={'ordering': ['-date_rendu'], 'permissions': [('can_view_own_rendus', 'Peut voir ses propres rendus')], 'verbose_name': 'Rendu de projet', 'verbose_name_plural': 'Rendus de projets'},
        ),
        migrations.AlterModelOptions(
            name='retard',
            options={'ordering': ['-date', '-heure_arrivee'], 'permissions': [('can_manage_retards', 'Peut gérer les retards')], 'verbose_name': 'Retard', 'verbose_name_plural': 'Retards'},
        ),
    ]
