# Generated by Django 5.2 on 2025-05-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsable_classe', '0002_alter_absence_options_alter_cahiertexte_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['-date', '-heure_debut'], 'verbose_name': 'Absence', 'verbose_name_plural': 'Absences'},
        ),
        migrations.AlterModelOptions(
            name='cahiertexte',
            options={'ordering': ['-date'], 'verbose_name': 'Cahier de texte', 'verbose_name_plural': 'Cahiers de texte'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-date'], 'verbose_name': 'Observation', 'verbose_name_plural': 'Observations'},
        ),
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['date_limite'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='renduprojet',
            options={'ordering': ['-date_rendu'], 'verbose_name': 'Rendu de projet', 'verbose_name_plural': 'Rendus de projets'},
        ),
        migrations.AlterModelOptions(
            name='retard',
            options={'ordering': ['-date', '-heure_arrivee'], 'verbose_name': 'Retard', 'verbose_name_plural': 'Retards'},
        ),
    ]
