# Generated by Django 5.2 on 2025-05-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsable_filiere', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='numero_etudiant',
        ),
    ]
