# Generated by Django 5.2 on 2025-05-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable_filiere', '0002_remove_eleve_numero_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='numero_etudiant',
            field=models.CharField(default='ETUD000', max_length=20, unique=True),
        ),
    ]
