# Generated by Django 5.2 on 2025-05-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable_filiere', '0004_alter_eleve_numero_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='numero_etudiant',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
